---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31123
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dep
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  minReadySeconds: 10 # how long a newly created pod should be ready before treated available
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: abh/examplenode:v1
        imagePullPolicy: "IfNotPresent"
        env:
          - name: MONGO_DB_NAME
            value: test
          - name: MONGO_DB_COLLECTION
            value: employee
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /ping
            port: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "20m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        volumeMounts:
        - name: environment-config
          mountPath: /config/environment.yaml
          subPath: environment.yaml
      volumes:
      - name: environment-config
        configMap:
          name: myapp-cm