# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.before(:all) do
    require './lib/desired_caps'
    @desired_caps = DesiredCaps.new(desired_caps)
  end
end

def desired_caps
  {
    caps: {
      platformName: "Android",
      platformVersion: ENV['PLATFORM_VERSION'],
      udid: ENV['UDID'],
      deviceName: "Android",
      app: ENV['APP_FILE'],
      appActivity: "com.atlantbh.navigator.MainActivity",
      appWaitActivity: "com.atlantbh.navigator.HomeActivity"
      },
    appium_lib: {
      debug: true,
      wait: 30,
      export_session: true,
      server_url: "http://localhost:#{ENV['PORT']}/wd/hub/"
    }
  }
end

