fixtures:
  repositories:
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
      ref: "2.1.0"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.6.0"
    java: "https://github.com/puppetlabs/puppetlabs-java"
    zypprepo: "https://github.com/deadpoint/puppet-zypprepo.git"
    staging: "https://github.com/nanliu/puppet-staging"
    archive: "https://github.com/camptocamp/puppet-archive"
  symlinks:
    "jenkins": "#{source_dir}"
