name: verify-step-function-outcome

on:
  workflow_dispatch:
env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_REGION: eu-central-1

jobs:
  verify_outcome:
    name: Verify Step Function Outcome
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ env.AWS_REGION }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Run VerifyStepFunctionOutcome tests
      run: npm run test verifyStepFunctionOutcome.test.js